"""add password_hash to volunteers

Revision ID: dc4e0415a6c8
Revises: ed28e30d8440
Create Date: 2026-04-04 10:03:58.041814

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'dc4e0415a6c8'
down_revision: Union[str, Sequence[str], None] = 'ed28e30d8440'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('volunteers', sa.Column('password_hash', sa.String(), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('volunteers', 'password_hash')
    # ### end Alembic commands ###
