"""add cascade deletes to task foreign keys

Revision ID: ed28e30d8440
Revises: a2b3c4d5e6f7
Create Date: 2026-04-04 03:08:17.729826

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'ed28e30d8440'
down_revision: Union[str, Sequence[str], None] = 'a2b3c4d5e6f7'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('tasks', 'volunteer_id',
               existing_type=sa.UUID(),
               nullable=True)
    op.drop_constraint(op.f('tasks_accident_id_fkey'), 'tasks', type_='foreignkey')
    op.drop_constraint(op.f('tasks_volunteer_id_fkey'), 'tasks', type_='foreignkey')
    op.create_foreign_key(None, 'tasks', 'volunteers', ['volunteer_id'], ['id'], ondelete='SET NULL')
    op.create_foreign_key(None, 'tasks', 'accidents', ['accident_id'], ['id'], ondelete='CASCADE')
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(None, 'tasks', type_='foreignkey')
    op.drop_constraint(None, 'tasks', type_='foreignkey')
    op.create_foreign_key(op.f('tasks_volunteer_id_fkey'), 'tasks', 'volunteers', ['volunteer_id'], ['id'])
    op.create_foreign_key(op.f('tasks_accident_id_fkey'), 'tasks', 'accidents', ['accident_id'], ['id'])
    op.alter_column('tasks', 'volunteer_id',
               existing_type=sa.UUID(),
               nullable=False)
    # ### end Alembic commands ###
